### ISSUE TITLE
RDflow

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1246]
Dle požadavků KNAV (konkrétně paní Nezbedové) je potřeba upravit chování RDFLOW:
- [ ] #1244 - chybné zobrazení UUDI v Materiálu
- [ ] #1245 - přidat sloupec PID
- [ ] #1243 - Seřazení nabídky sloupců podle abecedy
- [ ]  #1235 - neobjeví se info o chybě
- [ ]  #957 - chybová hláška při zakládání nového záměru
- [ ] Pokud jde o ročník, element mods:titleInfo:partNumber se zapisuje do pole ročník a ne do pole číslo
- [ ] Opravit tvorbu digitálního objektu z podzáměru
- [ ] Uložení pravidel AACR

**Comment by SykoraLukas** [comment]
Vše co je zaškrtnuto jsem otestoval na [testovacím serveru](proarc.inovatika.dev/api/) a funguje.

#1243 funguje jen pro nové uživatel nebo pro prohlížeč, který ještě nebyl přihlášen do rdflow. Problémem je možnost ručně přesouvat sloupce. Pokud si uživatel ručně změní pořadí sloupců, změní se i pořadí v nabídce zaškrtávání sloupců, které chce uživatel zobrazit. Bohužel toto provízání nedokážu nijak ovlivnit. Jde o vlastnost SmartGWT.

**Comment by nezbedova** [comment]
`Pokud jde o ročník, element mods:titleInfo:partNumber se zapisuje do pole ročník a ne do pole číslo`
To funguje. Ale nejde mi přepsat datum vydání ročníku, když založím ročník z Nový záměr. Opravím datum, ale stejně se mi zobrazí původní
![obrazek](https://user-images.githubusercontent.com/13831946/100615428-e12cb500-3317-11eb-9a44-9adf4b5c5ce1.png)
![obrazek](https://user-images.githubusercontent.com/13831946/100615503-f7d30c00-3317-11eb-85f7-ba7c3096eea5.png)

**Comment by nezbedova** [comment]
A když jsem si to chtěl zkontrolovat, zjistila jsem, že mi v horní liště chybí přepínač Metadata, abych mohla do xml  záznamu.

**Comment by SykoraLukas** [comment]
Editujete informace v digitálním objektu v ProArcu nebo v RDFlow? Mohla byste mi prosim vyfotit celou obrazovku? Děkuji

**Comment by nezbedova** [comment]
`Opravit tvorbu digitálního objektu z podzáměru`

Při vytvoření podzáměru přímo ze záměru se nezobrazí formulář pro tvorbu a editaci metadat. Podzáměr se hned založí a musí se upravit v bibliografickém záznamu. A hlavně odmazat nepotřebné údaje v xml.

**Comment by nezbedova** [comment]
V digitálním objektu. V RDFlow to nejde.

**Comment by SykoraLukas** [comment]
Informace z digitálního objektu se zpětně nepromítají do RDFlow. Tohle nefunguje ani u normálního záměru.

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/100616860-015d7380-331a-11eb-998a-fc1f59c8f0db.png)

**Comment by SykoraLukas** [comment]
Doplněna další funkcionalita:
- [ ] Možnost editovat podzáměr
- [ ] Propisování udajů do karty bibliografických údajů

**Comment by nezbedova** [comment]
Po založení Podzáměru za Záměru se pomocí tabulky zapíší údaje do Biblio, ale do levé tabulky až po novém uložení nebo refrash web stránky. Nevím, zda je to funkčnost nebo chyba. 
![obrazek](https://user-images.githubusercontent.com/13831946/100739799-f537eb80-33d7-11eb-884c-98894a07049d.png)
